print("Enter your last name")
lastname = input()
print("Enter your first name")
firstname = input()
print("Enter your age")
Age = input()
print('Sup,'+ lastname + " " + firstname + "!")
print(f"Sup {lastname} h{firstname}! Your age is {Age}.")
